# Generated by Django 2.2.4 on 2021-05-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_auto_20210524_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='author',
            field=models.ManyToManyField(default='', related_name='publishers', to='books_app.Books'),
        ),
    ]
