# Generated by Django 2.2.4 on 2021-05-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_app_pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshown',
            name='relaied_time',
            field=models.DateField(),
        ),
    ]
