# Generated by Django 2.2.4 on 2021-05-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='AddresS',
            new_name='address',
        ),
    ]
