# Generated by Django 2.2.4 on 2021-05-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_my_app', '0002_auto_20210524_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='confm_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='mamam', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='last', max_length=45),
            preserve_default=False,
        ),
    ]
