# Generated by Django 2.2.4 on 2021-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts_app', '0002_likes_thoughts'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughts',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_thoughts', to='thoughts_app.User'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
