# Generated by Django 2.2.4 on 2021-05-31 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts_app', '0003_auto_20210531_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thoughts',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='thoughts',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='thoughts',
            name='liked',
            field=models.ManyToManyField(default=True, related_name='liked_thoug', to='thoughts_app.User'),
        ),
        migrations.AddField(
            model_name='thoughts',
            name='posted',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_thoug', to='thoughts_app.User'),
        ),
    ]
